version: '3.7'
services:
  ###
  # builder
  ###
  builder:
    build: ./builder
    restart: always
    container_name: builder
    hostname: builder
    environment:
      PS1: '[builder \W]# '
    volumes:
      - work:/work
      - ./scripts:/scripts:delegated
      - ${BUILDER_SHARED_FOLDER}:/share:delegated
    # need this to debug
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

# use volumes for faster build and persistent data
volumes:
  work:
