apiVersion: v1
kind: Pod
metadata:
  name: alpine-builder
  namespace: build-rig
spec:
  containers:
    - name: alpine-builder
      image: localhost:32000/alpine_builder:latest
      imagePullPolicy: Always
      command: ["sleep","infinity"]
      volumeMounts:
        - name: work
          mountPath: /work
      resources:
        limits:
          memory: 2G
          cpu: 750m
  volumes:
    - name: work
      persistentVolumeClaim:
        claimName: build-rig-data
