apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-rig-data
  namespace: build-rig
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
